### PR TITLE
Fix: async/sync preloaders trigger at creation time, fixes #93

### LINKED ISSUE #93: preloadAsync does not trigger the async loading.

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

File: zoltar-core/src/main/java/com/spotify/zoltar/loaders/Preloader.java [hunk 1]
```diff
@@ -34,28 +36,44 @@
 public interface Preloader<M extends Model<?>> extends ModelLoader<M> {
 
   /**
-   * Returns a blocking {@link Preloader}. Blocks till the model is loaded
-   * or a {@link Duration} is met.
+   * Returns a blocking {@link Preloader}. Blocks at create time till the model is loaded.
+   */
+  static <M extends Model<?>> Function<ModelLoader<M>, Preloader<M>> preload() {
+    final Duration duration = Duration.ofDays(Integer.MAX_VALUE);
```
Comment (regadas) [inline zoltar-core/src/main/java/com/spotify/zoltar/loaders/Preloader.java]: no need for extra var here.
